name: Publish Docker image

# on: push  # This needs the with.ref in actions/checkout@v2.

on:
  release:
    types: [created, edited]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        # Add the following 'with' to run this using the
        # 'on: push' trigger
        with:
          ref: v1.4.0

      - name: Get the release
        run: echo "::set-output name=CURRENT_RELEASE::$(python -c 'from pierky.arouteserver.version import __version__; print(__version__)')"
        id: get_the_release

      - name: Is it a stable?
        run: echo "::set-output name=IS_STABLE_RELEASE::$(python -c 'from pierky.arouteserver.version import __version__; import re; import sys; re.match(r"^\d+\.\d+\.\d+$", __version__); sys.stdout.write(str(bool(re.match(r"^\d+\.\d+\.\d+$", __version__))))')"
        id: is_stable_release

      - name: Show the arguments
        run: echo "Release ${{ steps.get_the_release.outputs.CURRENT_RELEASE }} - stable ${{ steps.is_stable_release.outputs.IS_STABLE_RELEASE }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub (current release)
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: pierky/arouteserver:${{ steps.get_the_release.outputs.CURRENT_RELEASE }}

      - name: Push to Docker Hub (latest)
        if: steps.is_stable_release.outputs.IS_STABLE_RELEASE == 'True'
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: pierky/arouteserver:latest

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # This must be the DockerHub password, since AToW
          # Docker Hub doesn't allow to use tokens to update
          # the README.
          # https://github.com/peter-evans/dockerhub-description/issues/10
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pierky/arouteserver
          short-description: ARouteServer official Docker images
          readme-filepath: ./docker/README.md
